name: saltamontes
description: "Aplicaci√≥n de alto rendimiento para senderismo y monitoreo de rutas."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #state
  bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

  #navigation
  go_router: ^17.0.0
  url_launcher: ^6.3.2

  #map
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  mapbox_maps_flutter: ^2.18.0

  #permissions
  permission_handler: ^12.0.1

  #utils
  http: ^1.6.0
  path: ^1.9.1
  # image: ^4.7.2
  meta: ^1.16.0
  path_provider: ^2.1.5

  #database
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  uuid: ^4.5.1

  #visuals
  action_slider: ^0.7.0
  bootstrap_icons: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_lint: ^0.3.3
  flutter_lints: ^6.0.0

  #database
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
